# Generated by Django 4.2.29 on 2026-09-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0058_customuser_work_permit_extension_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employersettings",
            name="new_hire_invite_expiry_days",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text=(
                    "Days a new-hire registration link stays valid. "
                    "Leave blank to use the site default "
                    "(settings.NEW_HIRE_INVITE_EXPIRY_DAYS). "
                    "0 = never expire."
                ),
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="newhireinvite",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text=(
                    "When this registration link stops working. "
                    "Blank on older invites means no time limit."
                ),
                null=True,
            ),
        ),
    ]
