# Generated by Django 4.2.29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0059_newhireinvite_expires_at_and_employer_ttl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="work_permit_extension_date",
            field=models.DateField(
                blank=True,
                help_text=(
                    "Date the extension was submitted to IRCC. This is not an expiry. "
                    "Required when an extension letter is on file."
                ),
                null=True,
                verbose_name="Extension submitted",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="work_permit_extension_requested",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Check when a government extension or work-authorization letter "
                    "is on file and the employee is still legal to work. The letter "
                    "has no expiry date. Checked employees are left out of the "
                    "nightly 90/60/30 work-permit reminder."
                ),
                verbose_name="Extension letter on file",
            ),
        ),
    ]
