# Generated by Django 4.2.29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0060_work_permit_extension_letter_help"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkPermitMilestoneNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permit_expiration_date",
                    models.DateField(),
                ),
                (
                    "milestone",
                    models.PositiveSmallIntegerField(
                        choices=[(90, "90 days"), (60, "60 days"), (30, "30 days")]
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_permit_milestone_notices",
                        to="user.employer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_permit_milestone_notices",
                        to="user.customuser",
                    ),
                ),
            ],
            options={
                "ordering": ("-sent_at",),
                "unique_together": {("user", "permit_expiration_date", "milestone")},
            },
        ),
    ]
