# Generated by Django 4.2.29 on 2026-09-16 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0058_customuser_work_permit_extension_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DropboxCredentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("encrypted_refresh_token", models.TextField(blank=True)),
                (
                    "encrypted_app_key",
                    models.TextField(
                        blank=True,
                        help_text=(
                            "Optional per-tenant Dropbox app key. Leave blank to use "
                            "DROP_BOX_KEY from settings."
                        ),
                    ),
                ),
                (
                    "encrypted_app_secret",
                    models.TextField(
                        blank=True,
                        help_text=(
                            "Optional per-tenant Dropbox app secret. Leave blank to use "
                            "DROP_BOX_SECRET from settings."
                        ),
                    ),
                ),
                (
                    "account_email",
                    models.EmailField(
                        blank=True,
                        help_text="Non-secret identifier for this Dropbox account.",
                        max_length=254,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dropbox_credentials",
                        to="user.employer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dropbox credentials",
                "verbose_name_plural": "Dropbox credentials",
            },
        ),
    ]
