# Generated by Django 4.2.29 on 2026-09-21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("msg", "0041_delete_smsreply"),
    ]

    operations = [
        migrations.AddField(
            model_name="emaillog",
            name="subject",
            field=models.CharField(
                blank=True,
                help_text="Resolved subject that was sent (user input or template subject)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, blank=True, default=django.utils.timezone.now, null=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="html_body",
            field=models.TextField(
                blank=True,
                default="",
                help_text="In-app HTML body. Supports {{name}}, {{company_name}}, {{senior_contact_name}}. Image URLs should be public (Linode).",
            ),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="subject",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Email subject. Supports {{name}}, {{company_name}}, {{senior_contact_name}}.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="sendgrid_id",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional legacy SendGrid dynamic template ID. Leave blank for in-app templates; SendGrid is used as send transport only.",
            ),
        ),
    ]
