# Generated by Django 4.2.29 on 2026-09-22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msg", "0042_emailtemplate_in_app_fields_emaillog_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailtemplate",
            name="header_image_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional public header image URL (Linode). Shown at the top of preview and outbound HTML.",
                max_length=1024,
            ),
        ),
    ]
