# Generated by Django 4.2.29 on 2026-09-22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msg", "0043_emailtemplate_header_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailevent",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("in_app", "In-app"),
                    ("sendgrid", "SendGrid"),
                    ("compose", "Compose"),
                ],
                default="",
                help_text="in_app, sendgrid, or compose — from unique args when SendGrid has no template.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="emailevent",
            name="app_template_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="EmailTemplate.pk for in-app/legacy template sends (audit join).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="emaillog",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("in_app", "In-app"),
                    ("sendgrid", "SendGrid"),
                    ("compose", "Compose"),
                ],
                default="",
                help_text="in_app, sendgrid, or compose",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="emaillog",
            name="template_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="SendGrid template ID when one was used (empty for in-app HTML)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="include_in_report",
            field=models.BooleanField(
                default=False,
                help_text="Include this template in the employee compliance / click-engagement report.",
            ),
        ),
    ]
