# Generated by Django 4.2.29 on 2026-09-23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msg", "0044_email_source_and_audit_identity"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailtemplate",
            name="header_display_width",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (180, "Small (180px)"),
                    (240, "Compact (240px)"),
                    (280, "Medium (280px)"),
                    (360, "Large (360px)"),
                    (440, "Wide (440px)"),
                    (520, "Full (520px)"),
                ],
                default=280,
                help_text="How wide the header appears in the email, in pixels. Not stretched to the full column.",
            ),
        ),
    ]
