# Generated by Django 4.2.29 on 2026-09-23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msg", "0045_emailtemplate_header_display_width"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailtemplate",
            name="header_source_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Uncropped header original used to reframe the banner. Not sent in the email.",
                max_length=1024,
            ),
        ),
    ]
