# Generated by Django 4.2.29 on 2026-09-23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msg", "0046_emailtemplate_header_source_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailtemplate",
            name="header_space_below",
            field=models.PositiveSmallIntegerField(
                choices=[(8, "Tight"), (24, "Normal"), (48, "Roomy")],
                default=24,
                help_text="Space between the header picture and the message. Outlook uses a spacer row.",
            ),
        ),
    ]
