name: Django Tests

on:
  push:
    branches:
      - dev-v1.0.01
      - Multi-tenant-integration
  pull_request:
    branches:
      - dev-v1.0.01
      - Multi-tenant-integration

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
      TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
      SECRET_ENCRYPTION_KEY: ${{ secrets.SECRET_ENCRYPTION_KEY }}
      FERNET_PRIMARY_KEY: ${{ secrets.FERNET_PRIMARY_KEY }}
      SIN_HASH_SALT: ${{ secrets.SIN_HASH_SALT }}

      DB_NAME: testdb
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: 127.0.0.1
      DB_PORT: 5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            libcairo2-dev \
            pkg-config \
            python3-dev \
            libjpeg-dev \
            libz-dev \
            libfreetype6-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Django check
        run: |
          python arl/manage.py check

      - name: Run tests with coverage
        run: |
          coverage run arl/manage.py test arl.quiz.tests arl.quiz.test_checklist_import
          coverage report
